config/routes.rb
Rails.application.routes.draw do
  get 'trendz_sessions/new'

  root 'posts#home'

  get 'guide'   => 'latest_fashion_trendz#guide', path: 'la-la'
  get 'bios'    => 'latest_fashion_trendz#bios'
  get 'about'   => 'latest_fashion_trendz#about'
  get 'contact' => 'latest_fashion_trendz#contact'

  get 'home'            => 'posts#home'
  get 'dressesAndJeans' => 'posts#dressesAndJeans'
  get 'handbags'        => 'posts#handbags'
  get 'makeup'          => 'posts#makeup'
  get 'shoes'           => 'posts#shoes'

  get 'signup'  => 'fashion_trendz_users#new'

  get     'login'    => 'trendz_sessions#new'
  post    'login'    => 'trendz_sessions#create'
  delete  'logout'   => 'trendz_sessions#destroy'

  get     'index'    => 'comments#index'

  resources :fashion_trendz_users #, path: 'fashion-trendz-users'

  resources :account_activations, only: [:edit]

  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :posts,               only: [:show, :edit, :update, :create, :destroy]

  resources :comments

 namespace :api do 
  resources :comments #, defaults: { format: :json }
end

 match '*path' => 'posts#show', via: [:get, :post]

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
	before_action :get_usr,						only: [:edit, :update]
	before_action :val_usr,						only: [:edit, :update]
	before_action :exp_pass_res_tok, 	only: [:edit, :update]

  def new
  end

  def create
  	@fashion_trendz_user = FashionTrendzUser.find_by(email: params[:password_reset][:email].downcase)
		if @fashion_trendz_user
			@fashion_trendz_user.create_pass_res_dig
			@fashion_trendz_user.send_pass_res_em
			flash[:info] = "Email sent with password reset instructions"
			redirect_to root_url
		else
			flash.now[:danger] = "Email Addres NOT found!"
			render 'new'
		end
  end

  def edit
  end

  def update
  	if params[:fashion_trendz_user][:password].empty?
  		@fashion_trendz_user.errors.add(:password, "can't be empty")
  		render 'edit'
  	elsif @fashion_trendz_user.update_attributes(user_params)
  		log_in_trendz_user @fashion_trendz_user
  		flash[:success] = "Password has been reset.!"
  		redirect_to @fashion_trendz_user
  	else
  		render 'edit'
  	end
  end

  private

  	def user_params
  		params.require(:fashion_trendz_user).permit(:password, :password_confirmation)
  	end

		def get_usr
			@fashion_trendz_user = FashionTrendzUser.find_by(email: params[:email])
		end
# valid user?
		def val_usr
			unless (@fashion_trendz_user && @fashion_trendz_user.activated? && @fashion_trendz_user.authenticated?(:reset, params[:id]))
				redirect_to root_url
			end
		end
# expiration of reset tokn
		def exp_pass_res_tok
			if @fashion_trendz_user.pass_res_exp?
				flash[:danger] = "Password reset has expired. Enter Email for new isntructions."
				redirect_to new_password_reset_url
			end
		end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title, "Reset Password") %>

<!-- bootstrap -->
<div class="container-fluid">
<!-- bootstrap -->
 <div class="row cRowSignUpCont">

    <div class="col-xs-12">
      <div class="cDSignUp row">
        <h1>Reset Account Password</h1>
        <p class="col-sm-12 col-md-8 col-md-offset-2">Pick something smart to secure your account ... something, like combinations of styles, garments, accessories, etc. (eg. ArmANiGirLShOPpEr, etc...)</p>
      </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-8 col-md-offset-2">
      <%= render 'shared/error_messages' %> 
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <div class="cFormSignUp">
        <%= form_for(@fashion_trendz_user, url: password_reset_path(params[:id])) do |f| %>
  
          <%= render 'shared/error_messages', object: f.object %> 

          <%= hidden_field_tag :email, @fashion_trendz_user.email %>

          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control form-control2 cSignUpField' %>

          <%= f.label :password_confirmation, "Confirmation" %>
          <%= f.password_field :password_confirmation, class: 'form-control form-control2 cSignUpField' %>

          <%= f.submit "New Password", class: "btn btn-sm btn-primary btn-success cSignUpBtn" %>
        <% end %>
      </div>
    </div>

  <!-- bootstrap -->
  </div>
<!-- bootstrap -->
</div>

app/views/password_resets/new.html.erb
<% provide(:title, "Forgotten Password") %>
<!-- bootstrap -->
<div class="container-fluid">
<!-- bootstrap -->
<div class="row cRowSignUpCont">

  <div class="col-xs-12">
    <div class="cDSignUp">
      <h1>Forgotten Password</h1>
      <p>Reset your password via email.</p>
    </div>
  </div>

<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <div class="cFormSignUp">
    <%= form_for(:password_reset, url: password_resets_path) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control form-control2 cSignUpField' %>

      <%= f.submit "Reset", class: "btn btn-sm btn-primary btn-success cSignUpBtn" %>
    <% end %>

  </div>    
</div>

<!-- bootstrap -->
</div>
<!-- bootstrap -->
</div>