config/routes.rb
Rails.application.routes.draw do
  get 'trendz_sessions/new'

  root 'posts#home'

  get 'guide'   => 'latest_fashion_trendz#guide', path: 'la-la'
  get 'bios'    => 'latest_fashion_trendz#bios'
  get 'about'   => 'latest_fashion_trendz#about'
  get 'contact' => 'latest_fashion_trendz#contact'

  get 'home'            => 'posts#home'
  get 'dressesAndJeans' => 'posts#dressesAndJeans'
  get 'handbags'        => 'posts#handbags'
  get 'makeup'          => 'posts#makeup'
  get 'shoes'           => 'posts#shoes'

  get 'signup'  => 'fashion_trendz_users#new'

  get     'login'    => 'trendz_sessions#new'
  post    'login'    => 'trendz_sessions#create'
  delete  'logout'   => 'trendz_sessions#destroy'

  get     'index'    => 'comments#index'

  resources :fashion_trendz_users #, path: 'fashion-trendz-users'

  resources :account_activations, only: [:edit]

  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :posts,               only: [:show, :edit, :update, :create, :destroy]

  resources :comments

 namespace :api do 
  resources :comments #, defaults: { format: :json }
end

 match '*path' => 'posts#show', via: [:get, :post]

end

app/controllers/trendz_sessions_controller.rb
class TrendzSessionsController < ApplicationController
  def new
  end

  def create
  	@fashion_trendz_user = FashionTrendzUser.find_by(email: params[:trendz_session][:email].downcase)
		if @fashion_trendz_user && @fashion_trendz_user.authenticate(params[:trendz_session][:password])
        if @fashion_trendz_user.activated?
          log_in_trendz_user @fashion_trendz_user
          params[:trendz_session][:remember_me] == '1' ? remember(@fashion_trendz_user) : forget(@fashion_trendz_user)
          red_back_or @fashion_trendz_user
        else
          msg = "Account not activated. "
          msg += "Check your email for the activation link."
          flash[:warning] = message
          redirect_to root_url
        end
		else
			flash.now[:danger] = "Email/Password not valid"		
  		render 'new'
  	end
  end

  def destroy
    log_out_trendz_user if logged_in?
    redirect_to root_url
  end
end

app/helpers/trendz_sessions_helper.rb
module TrendzSessionsHelper

	def log_in_trendz_user(user) #log_in(user)
		session[:fashion_trendz_user_id] = user.id
	end

#returns current logged-in user (if any)
	def current_fashion_trendz_user #current_user
		if (user_id = session[:fashion_trendz_user_id])
			@curr_fashion_trendz_user ||= FashionTrendzUser.find_by(id: user_id)
		elsif (user_id = cookies.signed[:fashion_trendz_user_id])
#raise
			user = FashionTrendzUser.find_by(id: user_id)
			if user && user.authenticated?(:remember, cookies[:remember_token])
				log_in_trendz_user user
				@curr_fashion_trendz_user = user
			end
		end
	end	

	#true if user logged in
	def logged_in?
		!current_fashion_trendz_user.nil?
	end

	def remember(usr)
		usr.remember
		cookies.permanent.signed[:fashion_trendz_user_id] = usr.id
		cookies.permanent[:remember_token] = usr.remember_token
	end

	def curr_user?(usr)
		usr == current_fashion_trendz_user
	end

	def curr_user_admin?
		current_fashion_trendz_user.admin
	end

	def forget(usr)
		usr.forget
		cookies.delete(:fashion_trendz_user_id)
		cookies.delete(:remember_token)
	end	

	#log out
	def log_out_trendz_user
		forget(current_fashion_trendz_user)
		session.delete(:fashion_trendz_user_id)
		@curr_fashion_trendz_user = nil
	end

#friendly fw
	#redirect to stored location
	def red_back_or(df)
		redirect_to(session[:fw_url] || df)
		session.delete(:fw_url)
	end
	#stores url
	def store_loc(req = request.url)
		session[:fw_url] = req if request.get?
	end

end

app/views/trendz_sessions/new.html.erb
<% provide(:title, "Log In!") %>

<!-- bootstrap -->
<div class="container-fluid">
<!-- bootstrap -->
<div class="row cRowSignUpCont">

  <div class="col-xs-12">
    <div class="cDSignUp">
      <h1>Sign In to your Fashion Trendz Blog Account!</h1>
      <p>View, track of your favorite posts, purchases, wishlists, etc...</p>
    </div>
  </div>

<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <div class="cFormSignUp">
    <%= form_for(:trendz_session, url: login_path) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control form-control2 cSignUpField' %>

      <%= f.label :password %>
      <%= link_to new_password_reset_path, class: 'form-control2' do %>
        <small>(forgot password)</small>  
      <% end %>
      <%= f.password_field :password, class: 'form-control form-control2 cSignUpField' %>

      <%= f.label :remember_me, class: 'checkbox inline cCkBxLgIn' do %>
      <%= f.check_box :remember_me %>
          <span class="cRemSpn">Remember me on this computer</span>
      <% end %>

      <%= f.submit "Log In", class: "btn btn-sm btn-primary btn-success cSignUpBtn" %>
    <% end %>

    <p class="cPSignUp">New User <%= link_to "Fashion Trendz Blog Sign Up!", signup_path %></p>
  </div>    
</div>

<!-- bootstrap -->
</div>
<!-- bootstrap -->
</div>