config/routes.rb
Rails.application.routes.draw do
  get 'trendz_sessions/new'

  root 'posts#home'

  get 'guide'   => 'latest_fashion_trendz#guide', path: 'la-la'
  get 'bios'    => 'latest_fashion_trendz#bios'
  get 'about'   => 'latest_fashion_trendz#about'
  get 'contact' => 'latest_fashion_trendz#contact'

  get 'home'            => 'posts#home'
  get 'dressesAndJeans' => 'posts#dressesAndJeans'
  get 'handbags'        => 'posts#handbags'
  get 'makeup'          => 'posts#makeup'
  get 'shoes'           => 'posts#shoes'

  get 'signup'  => 'fashion_trendz_users#new'

  get     'login'    => 'trendz_sessions#new'
  post    'login'    => 'trendz_sessions#create'
  delete  'logout'   => 'trendz_sessions#destroy'

  get     'index'    => 'comments#index'

  resources :fashion_trendz_users #, path: 'fashion-trendz-users'

  resources :account_activations, only: [:edit]

  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :posts,               only: [:show, :edit, :update, :create, :destroy]

  resources :comments

 namespace :api do 
  resources :comments #, defaults: { format: :json }
end

 match '*path' => 'posts#show', via: [:get, :post]

end

app/models/post.rb
# Posts 
# 	-only admins can post Posts
# 	-any one can comment on a post once logged in

class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy

	default_scope -> { order(created_at: :desc) }

	validates :content, presence: true, length: { maximum: 2500 }

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :auth, only: [:create, :destroy, :edit]

#blog pages (mostly dynamic)
	def home
    @userPosts = Post.includes(comments: :fashion_trendz_user).paginate(page: params[:page], per_page: 6).order('created_at DESC')

# for use in partials to create a comment and save it
#   if the user is loggedi in    
    new_comment

    respond_to do |format|
      format.html
      format.js
    end

	end
  def dressesAndJeans
    @dressesAndJeans = post_lookup("dressesAndJeans")

# for use in partials to create a comment and save it
#   if the user is loggedi in
    new_comment
  end
  def handbags
    @handbags = post_lookup("handbags")

# for use in partials to create a comment and save it
#   if the user is loggedi in    
    new_comment
  end
  def makeup
    @makeup = post_lookup("makeup")

# for use in partials to create a comment and save it
#   if the user is loggedi in    
    new_comment
  end
  def shoes
    @shoes = post_lookup("shoes")

# for use in partials to create a comment and save it
#   if the user is loggedi in    
    new_comment
  end
  def show
    @viewPost = Post.includes(comments: :fashion_trendz_user).where(id: params["id"])

# for use in partials to create a comment and save it
#   if the user is loggedi in    
    new_comment    
  end

# creating/editing/destroying posts
  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:success] = "Post Created!"

# need to change to to elsewhere but not know where yet      
      redirect_to root_url
    else
      flash[:danger] = "Problem with submission! Post not created!"

# need to change to to elsewhere but not know where yet      
      redirect_to root_url
    end
  end
  def edit

  end
  def destroy
  end

  private

  # to restrict parameters allowed
  def post_params
    params.require(:post).permit(:title, :description, :category, :content)
  end

  def new_comment
    unless !logged_in?
      @newCom = current_fashion_trendz_user.comments.build
    end

  end

  def post_lookup(category)
    Post.includes(comments: :fashion_trendz_user).where(category: category).paginate(page: params[:page], per_page: 4).order(created_at: :desc)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<!-- POST!!!!! -->
<div class="post-<%= post.id %> cPost <%= post.category %>">
	<h1 class="cPstTl"><%= link_to post.title, post_path(:id => post.id) %></h1>

	<span class="cPostDate"><%= post.created_at %></span>

	<h3 class="cPostDesc"><%= post.description %></h3>

	<p class="cCont"><%= post.content %></p>

<!-- LAYING OUT COMMENTS -->
	<div class="iComWrapper">
		<div class="cComCont">	
			
			<h3 class="cH3Comm">Comments</h3>

			<% if !current_fashion_trendz_user %>
				<%= link_to login_path do %>
					<span class="cSpnComEn">Login To Comment</span>
					<% store_loc %>
				<% end %>
			<% else %>
				<%= content_tag :div, class: "" do %>
					<%= content_tag :div, class: "cComFrmCont" do %>

					<!-- passing info in locals hash to partial with:
								-new comment for angular option
								-the current post
								-func var to generalize partial
					-->
						<%= render partial: 'shared/comment_form', locals: { newCom: @newCom, post: post, func: "post"} %>

<!-- 	ANGULAR  -->
						<div class="cAngDivHmPg" ng-controller="commentsEditCtl" ng-init="comment.post_id = <%= post.id %>">
<!-- rendering comment and options for live updating via angular -->
							<get-post-user-id ng-init="comment.fashion_trendz_user_id = <%= current_fashion_trendz_user.id %>"></get-post-user-id>
						</div>
<!-- 	ANGULAR  -->

						<% end %>
					<% end %>
				<% end %>
		<!-- displaying only 4 latest posts and choosing to lay all of  them in the
					actual post page for this particular post -->
			<%= render  partial: "comments/comment", collection: post.comments.first(4), locals: { post: post} %>

<!-- cComCont -->		
		</div>
		<span class="cPostDate" style="float:none;color:black;font-family:f;font-weight:bold;margin-bottom:5%;display:block;margin-left:3%;">Click on Post Title to View ALL comments.<span>
<!-- iComWrapper -->
	</div>
<!-- cPost -->
</div>

app/views/posts/dressesAndJeans.html.erb
<% provide(:title, "Dresses And Jeans") %>

<!-- 	ANGULAR  -->
						<div>
<!-- rendering comment and options for live updating via angular -->
							<div ng-view></div>
						</div>
<!-- 	ANGULAR  -->	

<!-- bootstrap -->
<div class="container-fluid ">

	<h1 class="cDresJnH1">Dresses And Jeans</h1>

<!-- bootstrap -->
</div>

<!-- bootstrap -->
<div class="row">

	<div id="iDresJnPgWrapper">
		<div class="cDresJnPgCont">

		<div class="hidden-xs col-sm-2 col-md-2 col-lg-2">
			
			<aside class="cSide1Wrapper">

				<div class="cSide1Cont">
					<div class="cSide1Img">
						<%= link_to image_tag("city.jpg", class: "cSide1ImgTag"), "#" %>
					</div>

					<div class="cSide1Info">
						<h4>Link to Shoes!</h4>
						<p>Alert: shoes on sale!</p>
						<%= link_to "High Heels on Sale!", "#" %>
					</div>

					<div class="cSide1Img">
						<%= link_to image_tag("people.jpg"), "#" %>
					</div>

					<div class="cSide1Info">
						<h4>Link to Shoes!</h4>
						<p>Alert: shoes on sale!</p>
						<%= link_to "High Heels on Sale!", "#" %>
					</div>
					
					<div class="cSide1Img">
						<%= link_to image_tag("nightlife.jpg"), "#" %>
					</div>
					<div class="cSide1Info">
						<h4>Link to Shoes!</h4>
						<p>Alert: shoes on sale!</p>
						<%= link_to "High Heels on Sale!", "#" %>
					</div>

					<div class="cSide1Img">
						<%= link_to image_tag("model.jpg"), "#" %>
					</div>						
<!-- cSide1Cont -->					
				</div>
<!-- cSide1Wrapper -->				
			
			</aside>

		</div>

		<div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
<!-- main parragraph-->
		<div class="cDresJnWrapper">
			<div class="cDresJnCont">
				<div class="cDresJn">
					<p>"Copia caelestis solum concido. Facere auris cupiditas pel cras fugit titulus talus. Consuasor adflicto sed supra verecundia nulla considero minima.", "Amo volva patrocinor doloremque. Adeo quasi vito territo tabella blanditiis tabula illo. Victoria amplexus auditor tendo amaritudo cohors. Termes atrox asperiores ubi combibo abundans aestas ut.", "Cupio tantillus decet tenax confido. Confugo tero curiositas adinventitias tabula sodalitas. Quis eius libero beatus appono claustrum.", "Voluptatibus speciosus magnam. Inflammatio despirmatio vitium. Et doloribus vesper tandem spoliatio alias curis. Acquiro color paens.", "Suspendo universe a antepono acquiro vulpes spiculum. Coepi bis campana conicio curvo atqui eos. Absque culpo voluptatem. Abutor attollo victoria agnitio. Enim veritas subito recusandae illo auctus.", "Adfectus ut crinis. Dapifer deprecator correptius defetiscor cursim dolorem reprehenderit.
					</p>
					<p>"Copia caelestis solum concido. Facere auris cupiditas pel cras fugit titulus talus. Consuasor adflicto sed supra verecundia nulla considero minima.", "Amo volva patrocinor doloremque. Adeo quasi vito territo tabella blanditiis tabula illo. Victoria amplexus auditor tendo amaritudo cohors. Termes atrox asperiores ubi combibo abundans aestas ut.", "Cupio tantillus decet tenax confido. Confugo tero curiositas adinventitias tabula sodalitas. Quis eius libero beatus appono claustrum.", "Voluptatibus speciosus magnam. Inflammatio despirmatio vitium. Et doloribus vesper tandem spoliatio alias curis. Acquiro color paens.", "Suspendo universe a antepono acquiro vulpes spiculum. Coepi bis campana conicio curvo atqui eos. Absque culpo voluptatem. Abutor attollo victoria agnitio. Enim veritas subito recusandae illo auctus.", "Adfectus ut crinis. Dapifer deprecator correptius defetiscor cursim dolorem reprehenderit.
					</p>				
					</div>
				</div>
			</div>
<!-- main parragraph-->

			<div class="cPostSec">
				<h1 class="cHomeH1">Skinny Fit Vs. Comfortable</h1>

				<div class="cPostWrapper">

					<div id="iPagPsts" class="cPostCont">
						<!-- rendering posts with category: dressesAndJenas -->
						<%= render @dressesAndJeans %>
					<!-- cPostCont -->					
					</div>

					<!-- div with id to pick up at pagination.js.coffee -->
						<%= will_paginate @dressesAndJeans %>

		<!-- cPostWrapper -->				
				</div>
		<!-- cPostSec -->			
			</div>
		</div>

		<div class="col-xs-4 col-sm-2 col-md-2 col-lg-2 cSide2WrapperResp">
			
			<aside class="cSide2Wrapper">
			
				<div class="cSide2Cont">

					<div class="cSide2Info">
						<h4>Link to Shoes!</h4>
						<p>Alert: shoes on sale!</p>
						<%= link_to "High Heels on Sale!", "#" %>
					</div>
					<div class="cSide2Img">
						<%= link_to image_tag("model.jpg"), "#" %>
					</div>

					<div class="cSide2Info">
						<h4>Link to Shoes!</h4>
						<p>Alert: shoes on sale!</p>
						<%= link_to "High Heels on Sale!", "#" %>
					</div>
					<div class="cSide2Img">
						<%= link_to image_tag("nightlife.jpg"), "#" %>
					</div>					
					<div class="cSide2Info">
						<h4>Link to Shoes!</h4>
						<p>Alert: shoes on sale!</p>
						<%= link_to "High Heels on Sale!", "#" %>
					</div>
					<div class="cSide2Img">
						<%= link_to image_tag("people.jpg"), "#" %>
					</div>
					<div class="cSide2Info">
						<h4>Link to Shoes!</h4>
						<p>Alert: shoes on sale!</p>
						<%= link_to "High Heels on Sale!", "#" %>
					</div>
					<div class="cSide2Img">
						<%= link_to image_tag("city.jpg"), "#" %>
					</div>						
<!-- cSide1Cont -->					
				</div>

			</aside>

		</div>

		<!-- cHmPgCont -->
			</div>
		<!-- iHmPgWrapper -->
			</div>

	<!-- bootstrap -->
</div>

app/views/posts/dressesAndJeans.js.erb
/* to aide in pagination where posts are rendered */
$('#iPagPsts').append("<%= j render( partial: 'posts/post', collection: @dressesAndJeans) %>");

<% if @dressesAndJeans.next_page %>
	$('.pagination').replaceWith('<%= j will_paginate(@dressesAndJeans) %>');
<% else %>
	$(window).off('scroll');
	$('.pagination').remove();
<% end %>

app/views/posts/handbags.html.erb
<% provide(:title, "Handbags") %>

<!-- bootstrap -->
<div class="container-fluid ">

	<h1 class="cHndbgH1">Handbags/Purses</h1>

<!-- bootstrap -->
<div class="row">

	<div id="iHmPgWrapper">
		<div class="cHmPgCont">

		<div class="hidden-xs col-sm-2 col-md-2 col-lg-2">
			
			<aside class="cSide1Wrapper">

				<div class="cSide1Cont">
					<div class="cSide1Img">
						<%= link_to image_tag("city.jpg", class: "cSide1ImgTag"), "#" %>
					</div>

					<div class="cSide1Info">
						<h4>Link to Shoes!</h4>
						<p>Alert: shoes on sale!</p>
						<%= link_to "High Heels on Sale!", "#" %>
					</div>

					<div class="cSide1Img">
						<%= link_to image_tag("people.jpg"), "#" %>
					</div>

					<div class="cSide1Info">
						<h4>Link to Shoes!</h4>
						<p>Alert: shoes on sale!</p>
						<%= link_to "High Heels on Sale!", "#" %>
					</div>
					
					<div class="cSide1Img">
						<%= link_to image_tag("nightlife.jpg"), "#" %>
					</div>
					<div class="cSide1Info">
						<h4>Link to Shoes!</h4>
						<p>Alert: shoes on sale!</p>
						<%= link_to "High Heels on Sale!", "#" %>
					</div>

					<div class="cSide1Img">
						<%= link_to image_tag("model.jpg"), "#" %>
					</div>						
<!-- cSide1Cont -->					
				</div>
<!-- cSide1Wrapper -->				
			
			</aside>
			
		</div>
		
		<div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">

		<!-- main parragraph-->
		<div class="cHndbgWrapper">
			<div class="cHndbgCont">
				<div class="cHndbg">
					<p>"Copia caelestis solum concido. Facere auris cupiditas pel cras fugit titulus talus. Consuasor adflicto sed supra verecundia nulla considero minima.", "Amo volva patrocinor doloremque. Adeo quasi vito territo tabella blanditiis tabula illo. Victoria amplexus auditor tendo amaritudo cohors. Termes atrox asperiores ubi combibo abundans aestas ut.", "Cupio tantillus decet tenax confido. Confugo tero curiositas adinventitias tabula sodalitas. Quis eius libero beatus appono claustrum.", "Voluptatibus speciosus magnam. Inflammatio despirmatio vitium. Et doloribus vesper tandem spoliatio alias curis. Acquiro color paens.", "Suspendo universe a antepono acquiro vulpes spiculum. Coepi bis campana conicio curvo atqui eos. Absque culpo voluptatem. Abutor attollo victoria agnitio. Enim veritas subito recusandae illo auctus.", "Adfectus ut crinis. Dapifer deprecator correptius defetiscor cursim dolorem reprehenderit.
					</p>
					<p>"Copia caelestis solum concido. Facere auris cupiditas pel cras fugit titulus talus. Consuasor adflicto sed supra verecundia nulla considero minima.", "Amo volva patrocinor doloremque. Adeo quasi vito territo tabella blanditiis tabula illo. Victoria amplexus auditor tendo amaritudo cohors. Termes atrox asperiores ubi combibo abundans aestas ut.", "Cupio tantillus decet tenax confido. Confugo tero curiositas adinventitias tabula sodalitas. Quis eius libero beatus appono claustrum.", "Voluptatibus speciosus magnam. Inflammatio despirmatio vitium. Et doloribus vesper tandem spoliatio alias curis. Acquiro color paens.", "Suspendo universe a antepono acquiro vulpes spiculum. Coepi bis campana conicio curvo atqui eos. Absque culpo voluptatem. Abutor attollo victoria agnitio. Enim veritas subito recusandae illo auctus.", "Adfectus ut crinis. Dapifer deprecator correptius defetiscor cursim dolorem reprehenderit.
					</p>
				</div>
			</div>
		</div>
<!-- main parragraph-->

			<div class="cPostSec">
				<h1 class="cHomeH1">Fendi, Fendi, Fendi!</h1>


				<div class="cPostWrapper">

					<div  id="iPagPsts" class="cPostCont">
						<!-- rendering posts with category: handbags -->
						<%= render @handbags %>
		<!-- cPostCont -->					
					</div>
					<%=  will_paginate @handbags %>
		<!-- cPostWrapper -->				
				</div>
		<!-- cPostSec -->			
			</div>
		</div>

		<div class="col-xs-4 col-sm-2 col-md-2 col-lg-2 cSide2WrapperResp">
			
			<aside class="cSide2Wrapper">
			
				<div class="cSide2Cont">

					<div class="cSide2Info">
						<h4>Link to Shoes!</h4>
						<p>Alert: shoes on sale!</p>
						<%= link_to "High Heels on Sale!", "#" %>
					</div>
					<div class="cSide2Img">
						<%= link_to image_tag("model.jpg"), "#" %>
					</div>

					<div class="cSide2Info">
						<h4>Link to Shoes!</h4>
						<p>Alert: shoes on sale!</p>
						<%= link_to "High Heels on Sale!", "#" %>
					</div>
					<div class="cSide2Img">
						<%= link_to image_tag("nightlife.jpg"), "#" %>
					</div>					
					<div class="cSide2Info">
						<h4>Link to Shoes!</h4>
						<p>Alert: shoes on sale!</p>
						<%= link_to "High Heels on Sale!", "#" %>
					</div>
					<div class="cSide2Img">
						<%= link_to image_tag("people.jpg"), "#" %>
					</div>
					<div class="cSide2Info">
						<h4>Link to Shoes!</h4>
						<p>Alert: shoes on sale!</p>
						<%= link_to "High Heels on Sale!", "#" %>
					</div>
					<div class="cSide2Img">
						<%= link_to image_tag("city.jpg"), "#" %>
					</div>						
<!-- cSide1Cont -->					
				</div>
			
			</aside>

		</div>

		<!-- cHmPgCont -->
			</div>
		<!-- iHmPgWrapper -->
			</div>

	<!-- bootstrap -->
</div>

app/views/posts/handbags.js.erb
/* to aide in pagination where posts are rendered */
$('#iPagPsts').append("<%= j render( partial: 'posts/post', collection: @handbags) %>");

<% if @handbags.next_page %>
	$('.pagination').replaceWith('<%= j will_paginate(@handbags) %>');
<% else %>
	$(window).off('scroll');
	$('.pagination').remove();
<% end %>

app/views/posts/home.html.erb
<!-- 
	HOMEPAGE
-->	
<% content_for(:title, "Trendz Blog Home Page") %>

<!-- bootstrap -->
<div class="row">

	<div id="iHmPgWrapper">
		<div class="cHmPgCont">

		<div class="col-xs-3 col-sm-4 col-md-4 col-lg-4 cSide2WrapperResp">
		
			<aside class="cSide1HomeWrapper">
				<div class="cSideCont">

					<div class="cSide2InfoSoc">
						<h4>Social Media</h4>
						<p>Social media buttons: twitter, facebook, sharing, etc...</p>
						<p><span><%= link_to "Twitter!", "#" %></span></p>
						<p><span><%= link_to "Facebook!", "#" %></span></p>
						<p><span><%= link_to "Instagram!", "#" %></span></p>
						<p><span><%= link_to "Share!", "#" %></span></p>
					</div>

					<div class="row">
						<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
							<div class="cSide2ImgPost1">
								<%= link_to image_tag("model.jpg"), "#" %>
							</div>
						</div>
						<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
							<div class="cSide2ImgPost2">
								<%= link_to image_tag("nightlife.jpg"), "#" %>
							</div>						
						</div>
					</div>

					<div class="cSide2InfoPost">
						<h4>Most popular comments:</h4>
						<span style="color:blue;font-family:f;font-weight:bold">Filter by id# (try 0-790)</span>
						<p class="cPopCom">
<!-- 	ANGULAR  -->
						<div>
<!-- rendering comment and options for live updating via angular -->
							<div ng-view></div>
						</div>
<!-- 	ANGULAR  -->						
						</p>
						<p class="cPopCom hidden-xs">
						</p>

	

					</div>

					<div class="row">
						<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
							<div class="cSide2ImgPost1">
								<%= link_to image_tag("nightlife.jpg"), "#" %>
							</div>	
						</div>
						<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">						
							<div class="cSide2ImgPost2">
								<%= link_to image_tag("model.jpg"), "#" %>
							</div>
						</div>
					</div>							

					<div class="cSide2InfoPost">
						<h4>Link to Shoes!</h4>
						<p>Alert: shoes on sale!</p>
						<%= link_to "High Heels on Sale!", "#" %>
					</div>

					<div class="row">
						<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
							<div class="cSide2ImgPost1">
								<%= link_to image_tag("people.jpg"), "#" %>
							</div>
						</div>
						<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">					
							<div class="cSide2ImgPost2">
								<%= link_to image_tag("city.jpg"), "#" %>
							</div>
						</div>
					</div>							

					
<!-- cSide1Cont -->					
				</div>
<!-- cSide2Wrapper -->
			</aside>
<!-- bootstrap -->
		</div>		
		
			<div class="col-xs-11 col-sm-8 col-md-8 col-lg-8">
				<div class="cPostSec">
					<h1 class="cHomeH1">Fashion Trendz Blog Post</h1>


					<div class="cPostWrapper">

						<div id="iPagPsts" class="cPostCont">
							<!-- rendering posts with category:  all/any-->
							<%= render @userPosts %>
						<!-- cPostCont -->					
						</div>

			<!-- div with id to pick up at pagination.js.coffee -->
						<%= will_paginate @userPosts %>
					
			<!-- cPostWrapper -->				
					</div>
			<!-- cPostSec -->			
				</div>
			</div>

		<!-- cHmPgCont -->
		</div>

	<!-- iHmPgWrapper -->
	</div>

	<!-- bootstrap -->
</div>

app/views/posts/home.js.erb
/* to aide in pagination where posts are rendered */
$('#iPagPsts').append("<%= j render( partial: 'posts/post', collection: @userPosts) %>");

<% if @userPosts.next_page %>
	$('.pagination').replaceWith('<%= j will_paginate(@userPosts) %>');
<% else %>
	$(window).off('scroll');
	$('.pagination').remove();
<% end %>

app/views/posts/makeup.js.erb
/* to aide in pagination where posts are rendered */
$('#iPagPsts').append("<%= j render( partial: 'posts/post', collection: @makeup) %>");

<% if @makeup.next_page %>
	$('.pagination').replaceWith('<%= j will_paginate(@makeup) %>');
<% else %>
	$(window).off('scroll');
	$('.pagination').remove();
<% end %>

app/views/posts/shoes.js.erb
/* to aide in pagination where posts are rendered */
$('#iPagPsts').append("<%= j render( partial: 'posts/post', collection: @shoes) %>");

<% if @shoes.next_page %>
	$('.pagination').replaceWith('<%= j will_paginate(@shoes) %>');
<% else %>
	$(window).off('scroll');
	$('.pagination').remove();
<% end %>

app/views/posts/show.html.erb
<!--  
	-show particular post
-->
<% content_for(:title, @viewPost[0].title) %>

<!-- bootstrap -->
<div class="row">

	<div id="iHmPgWrapper">
		<div class="cHmPgCont">
		
		<div class="col-xs-11 col-sm-8 col-md-8 col-lg-8">
			
			<aside class="cPostSec">

				<h1 class="cHomeH1">Fashion Trendz Blog Post</h1>


				<div class="cPostWrapper">
					<div class="cPostCont">

						<%= render @viewPost %>

		<!-- cPostCont -->					
					</div>
		<!-- cPostWrapper -->				
				
				</aside>

		<!-- cPostSec -->			
			</div>
		</div>

		<div class="col-xs-3 col-sm-4 col-md-4 col-lg-4 cSide2WrapperResp">
			<div class="cSide2WrapperPost">
				<div class="cSide2Cont">

					<div class="cSide2InfoSoc">
						<h4>Social Media</h4>
						<p>Social media buttons: twitter, facebook, sharing, etc...</p>
						<p><span><%= link_to "Twitter!", "#" %></span></p>
						<p><span><%= link_to "Facebook!", "#" %></span></p>
						<p><span><%= link_to "Instagram!", "#" %></span></p>
						<p><span><%= link_to "Share!", "#" %></span></p>
					</div>

					<div class="row">
						<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
							<div class="cSide2ImgPost1">
								<%= link_to image_tag("model.jpg"), "#" %>
							</div>
						</div>
						<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
							<div class="cSide2ImgPost2">
								<%= link_to image_tag("nightlife.jpg"), "#" %>
							</div>						
						</div>
					</div>

					<div class="cSide2InfoPost">
						<h4>Most popular comments:</h4>
						<h5></h5>
						<p class="cPopCom"><%= show_popular_comments(@viewPost) %>
						</p>
						<%= link_to "High Heels on Sale!", "#" %>
						<p class="cPopCom hidden-xs"><%= show_popular_comments(@viewPost) %>
						</p>	

					</div>

					<div class="row">
						<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
							<div class="cSide2ImgPost1">
								<%= link_to image_tag("nightlife.jpg"), "#" %>
							</div>	
						</div>
						<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">						
							<div class="cSide2ImgPost2">
								<%= link_to image_tag("model.jpg"), "#" %>
							</div>
						</div>
					</div>							

					<div class="cSide2InfoPost">
						<h4>Link to Shoes!</h4>
						<p>Alert: shoes on sale!</p>
						<%= link_to "High Heels on Sale!", "#" %>
					</div>

					<div class="row">
						<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
							<div class="cSide2ImgPost1">
								<%= link_to image_tag("people.jpg"), "#" %>
							</div>
						</div>
						<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">					
							<div class="cSide2ImgPost2">
								<%= link_to image_tag("city.jpg"), "#" %>
							</div>
						</div>
					</div>							

					
<!-- cSide1Cont -->					
				</div>
			
			</aside>
			
		</div>

		<!-- cHmPgCont -->
			</div>

		<!-- iHmPgWrapper -->
			</div>

	<!-- bootstrap -->
</div>