config/routes.rb
Rails.application.routes.draw do
  get 'trendz_sessions/new'

  root 'posts#home'

  get 'guide'   => 'latest_fashion_trendz#guide', path: 'la-la'
  get 'bios'    => 'latest_fashion_trendz#bios'
  get 'about'   => 'latest_fashion_trendz#about'
  get 'contact' => 'latest_fashion_trendz#contact'

  get 'home'            => 'posts#home'
  get 'dressesAndJeans' => 'posts#dressesAndJeans'
  get 'handbags'        => 'posts#handbags'
  get 'makeup'          => 'posts#makeup'
  get 'shoes'           => 'posts#shoes'

  get 'signup'  => 'fashion_trendz_users#new'

  get     'login'    => 'trendz_sessions#new'
  post    'login'    => 'trendz_sessions#create'
  delete  'logout'   => 'trendz_sessions#destroy'

  get     'index'    => 'comments#index'

  resources :fashion_trendz_users #, path: 'fashion-trendz-users'

  resources :account_activations, only: [:edit]

  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :posts,               only: [:show, :edit, :update, :create, :destroy]

  resources :comments

 namespace :api do 
  resources :comments #, defaults: { format: :json }
end

 match '*path' => 'posts#show', via: [:get, :post]

end

app/views/layouts/_ie_shim.html.erb
<!-- shim for IE < 9v -->

	<!--[if lt IE 9]>
		<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
		</script>
	<![endif]-->

<!-- shim for IE < 9v -->

app/views/layouts/_latest_fashion_trendz_blog_footer.html.erb
<footer id="footer">

<!-- for bootstrap -->
<div class="container-fluid">
<!-- for bootstrap -->
<div class="row">

    <div class="cDFCred col-xs-5 col-xs-2 col-md-3 col-lg-3">
      <span class"cSpCred">Web Services</span>
      <%= link_to 'RunTechServices.com', "http://www.RunTechServices.com", target: '_blank', title: "Web Master", rel: 'external', class: 'cWbMstr' %>
    </div>

		<div class="cFooterMenu col-xs-7 col-sm-7 col-sm-7 col-lg-7">
<div class="row">
  			<section class="iSecFootMenu col-xs-4 col-sm-6 col-md-6 col-lg-6">
          <ul class="cUFootMenu">
            <li class="cFLiMenu">
              <%= link_to 'Home', home_path, target: '_self', title: "latest Fashion trendz home page", rel: 'help' %>
            </li> 
              <%= link_to 'Dresses/Jeans', dressesAndJeans_path, target: '_self', title: "latest Fashion trendz handbag sale", rel: 'help' %>
            </li>          
            <li class="cFLiMenu">
              <%= link_to 'Handbags', handbags_path, target: '_self', title: "latest Fashion trendz handbag sale", rel: 'help' %>
            </li>
            <li class="cFLiMenu">
              <%= link_to 'MakeUp', makeup_path, target: '_self', title: "Fashion trendz make up tips", rel: 'help' %>
            </li>
            <li class="cFLiMenu">
              <%= link_to "Shoes!", shoes_path, target: '_self', title: "Fashion trendz shoes, shoes, shoes!!!", rel: 'help' %>
            </li>                                                       

  <!-- for logged in users -->
  <% if logged_in? %>               
            <li class="cFLiMenu" role="presentation">
              <%= link_to 'Log Out!', logout_path, method: "delete", target: '_self', title: "latest Fashion trendz member log out", rel: 'help' %>
             </li>
            <li class="cFLiMenu" role="presentation">
              <%= link_to 'Profile', current_fashion_trendz_user, target: '_self', title: "latest Fashion trendz member log out", rel: 'help' %>
            </li> 
    <% if current_fashion_trendz_user.admin == true %>
            <li class="cFLiMenu" role="presentation">
              <%= link_to 'Users', fashion_trendz_users_path, target: '_self', title: "fahon trendz user list", rel: 'help' %>
            </li>
    <% end %>     
  <% else %>
            <li class="cFLiMenu" role="presentation">
              <%= link_to 'Login', login_path, target: '_self', title: "Fashion trendz  log in", rel: 'help' %>
            </li> 
            <li class="cFLiMenu" role="presentation ">
              <%= link_to 'Sign Up', signup_path, target: '_self', title: "Fashion trendz sign up", rel: 'help' %>
            </li>                             
  <% end %>
          </ul>
  <!-- end of iSecFootMenu -->        
        </section>

        <section class="iSecFootMenu2 col-xs-6 col-sm-5 col-md-5 col-lg-5">
          <ul class="cFLiMenu">
            <li class="dropdown cFLiMenu cFLiDrop" role="presentation">               
              <%= link_to '#', target: '_self', title: "Fashion trendz blog home page", rel: 'help',  class: "dropdown-toggle", :'data-toggle' => "dropdown", role: "button", :'aria-haspopup' => 'true', :'aria-expanded' => 'false' do %>
                <span class="caret">Guide</span>
              <% end %>       
              <ul class="dropdown-menu">
                <li class="">
                  <%= link_to "Advice", '#', target: '_self', title: "latest Fashion trendz fashion advice", rel: 'help' %>
                </li>
                <li class="">
                  <%= link_to "Guide", guide_path, target: '_self', title: "latest Fashion trendz cloting & accessories guide", rel: 'help' %>
                </li>
                <li class="">
                  <%= link_to "Bios", bios_path, target: '_self', title: "latest Fashion trendz fashion world biographies", rel: 'help' %>
                </li>
              </ul>
            </li>
            <li class="dropdown cFLiMenu cFLiDrop2" role="presentation">
              <%= link_to '#', target: '_self', title: "Fashion trendz info", rel: 'help',  class: "dropdown-toggle", :'data-toggle' => "dropdown", role: "button", :'aria-haspopup' => 'true', :'aria-expanded' => 'false' do %>
                <span class="caret">Info</span>
              <% end %>
              <ul class="dropdown-menu">
                <li class="cFLiMenu">
                  <%= link_to "Contact", contact_path, target: '_self', title: "latest Fashion trendz contact information", rel: 'help'  %>
                </li>
                <li class="cFLiMenu">
                  <%= link_to "About", about_path, target: '_self', title: "latest Fashion trendz website/blog information", rel: 'help'  %>
                </li> 
              </ul>
            </li>
          </ul>
  <!-- end of iSecFootMenu2 -->
        </section>  
</div> 

<!-- cFooterMenu -->
    </div>

<!-- for bootstrap -->
</div>
<!-- for bootstrap -->
</div>
</footer>

app/views/layouts/_latest_fashion_trendz_blog_header.html.erb
<header>
	<div id="iHeaderCont">
		<div id="iHeaderTopDiv">
	    <div class="cHeader">

<!-- for bootstrap -->
<div class="container-fluid">
<!-- for bootstrap -->
<div class="row">

<!-- for logged in users -->
	<div id="iDLgd" class="cDLgd col-xs-6 col-md-6">
		<div class="row">			
			<ul class="cULgd ">

				<li class="dropdown cLiMenu col-xs-3 col-sm-3 col-md-3 col-lg-3" role="presentation">								
					<%= link_to '#', target: '_self', title: "Fashion trendz blog home page", rel: 'help',  class: "dropdown-toggle", :'data-toggle' => "dropdown", role: "button", :'aria-haspopup' => 'true', :'aria-expanded' => 'false' do %>
							<span class="visible-sm visible-md visible-lg caret">Guide</span><span class="glyphicon glyphicon-home visible-xs"></span>
					<% end %>						
					<ul class="dropdown-menu">
						<li class="cLiMenu">
							<%= link_to "Advice", '#', target: '_self', title: "latest Fashion trendz fashion advice", rel: 'help' %>
						</li>
						<li class="cLiMenu">
							<%= link_to "Guide", guide_path, target: '_self', title: "latest Fashion trendz cloting & accessories guide", rel: 'help' %>
						</li>
						<li class="cLiMenu">
							<%= link_to "Bios", bios_path, target: '_self', title: "latest Fashion trendz fashion world biographies", rel: 'help' %>
						</li>
					</ul>
				</li>												

<% if logged_in? %>								
				<li class="cLiMenu col-xs-3 col-md-3" role="presentation">
					<%= link_to logout_path, method: "delete", target: '_self', title: "latest Fashion trendz member log out", rel: 'help' do %>
							<span class="visible-sm visible-md visible-lg">Log-&gt;</span><span class="glyphicon glyphicon-log-out visible-xs"></span>									
					<% end %>
				</li>
				<li class="dropdown cLiMenu col-xs-3 col-md-3" role="presentation">
					<%= link_to '#', target: '_self', title: "latest Fashion trendz member log out", rel: 'help', class: 'dropdown-toggle', :'data-toggle' => 'dropdown', role: 'button', :'aria-haspopup' => 'true', :'aria-expanded' => 'false' do %>
							<span class="visible-sm visible-md visible-lg">Profile</span><span class="glyphicon glyphicon-user visible-xs"></span>
					<% end %>
						<ul class="dropdown-menu cULgd">
							<li class="cLiMenu">
								<%= link_to "Edit Profile", edit_fashion_trendz_user_path(current_fashion_trendz_user), target: '_self', title: "latest Fashion trendz contact information", rel: 'help'  %>
							</li>
							<li class="cLiMenu">
								<%= link_to "Profile", current_fashion_trendz_user, target: '_self', title: "latest Fashion trendz contact information", rel: 'help'  %>
							</li>										
						</ul>								
				</li>	
<% if current_fashion_trendz_user.admin == true %>
				<li class="cLiMenu col-xs-3 col-md-3" role="presentation">
					<%= link_to fashion_trendz_users_path, target: '_self', title: "fahion trendz user list", rel: 'help' do %>
						<span class="visible-sm visible-md visible-lg">Users</span><span class="glyphicon glyphicon-th-list visible-xs"></span>
					<% end %>
				</li>
<% end %>			
<% else %>
				<li class="cLiMenu col-xs-3 col-md-3" role="presentation">
					<%= link_to login_path, target: '_self', title: "Fashion trendz  log in", rel: 'help' do %>
							<span class="visible-sm visible-md visible-lg">Login</span><span class="glyphicon glyphicon-log-in visible-xs"></span>
					<% end %>
				</li>	
				<li class="cLiMenu col-xs-3 col-md-3" role="presentation	">
					<%= link_to signup_path, target: '_self', title: "Fashion trendz sign up", rel: 'help' do %>
							<span class="visible-sm visible-md visible-lg">Sign Up</span><span class="glyphicon glyphicon-pencil visible-xs"></span>
					<% end %>
				</li>															
<% end %>
					<li class="dropdown cLiMenu col-xs-3" role="presentation">		
					<%= link_to '#', target: '_self', title: "Fashion trendz info", rel: 'help',  class: "dropdown-toggle", :'data-toggle' => "dropdown", role: "button", :'aria-haspopup' => 'true', :'aria-expanded' => 'false' do %>
								<span class="visible-sm visible-md visible-lg caret">Info</span>
								<span class="glyphicon glyphicon-info-sign visible-xs caret"></span>
					<% end %>
					<ul class="dropdown-menu">
						<li class="cLiMenu">
							<%= link_to "Contact", contact_path, target: '_self', title: "latest Fashion trendz contact information", rel: 'help'  %>
						</li>
						<li class="cLiMenu">
							<%= link_to "About", about_path, target: '_self', title: "latest Fashion trendz website/blog information", rel: 'help'  %>
						</li>	
					</ul>
				</li>
			</ul>
		</div>
	</div>

	<!-- image logo -->
	<div class="cHeaderImgLogo col-xs-5 col-sm-4 col-md-4 col-lg-4 ">
		<%= link_to image_tag("latestFashionTrendzPictureLogo.png", alt: "Latest Fashion Trendz letter site logo", title: "Website logo", class: 'cLogoPic col-xs-12 col-sm-12 col-md-12 col-lg-12'), root_path, target: '_self', title:	"latest Fashion trendz blog home page", rel: 'help'	%>
	</div>
<!--  text logo -->
	<div class="cHeaderTxtLogo col-xs-7 col-sm-7 col-sm-offset-0 col-md-7 col-md-offset-0 col-lg-7 col-lg-offset-0 ">
		<%= link_to image_tag("latestFashionTrendzLetterLogo.png", alt: "Latest Fashion Trendz letter site logo", title: "Website logo", class: 'cLogoText col-xs-12 col-sm-12 col-md-12 col-lg-12'), root_path, target: '_self', title: 	"latest Fashion trendz blog home page", rel: 'help' %>			
	</div>

<!-- bootstrap row -->
</div>
<!-- bootstrap container-fluid</div> -->


	<!--MENU CONTAINER -->
	<div id="iMenuCont" class="cMenuCont">
<!-- for bootstrap<div class="container-fluid"
 -->
<!-- for bootstrap -->
<div class="row">
	<div class="cMenu " role="group">			
		<ul class="cUMenu col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<li class="cLiMenu col-xs-2 col-sm-2 col-md-2 col-lg-2">
				<%= link_to root_path, target: '_self', title: "latest Fashion trendz member log out", rel: 'help' do %>
						<span class="visible-sm visible-md visible-lg">Home</span><span class="glyphicon glyphicon-home visible-xs"></span>	
				<% end %>								
			</li>

			<li class="cLiMenu col-xs-2 col-sm-2 col-md-3 col-lg-3">
				<%= link_to dressesAndJeans_path, target: '_self', title: "latest Fashion trendz handbag sale", rel: 'help' do %>
					<span class="visible-sm visible-md visible-lg">Dresses/Jeans</span><span class="visible-xs cBagG"><%= image_tag 'dress.png' %></span>
				<% end %>
			</li>
			<li class="cLiMenu col-xs-2 col-sm-2 col-md-2 col-lg-3">
				<%= link_to handbags_path, target: '_self', title: "latest Fashion trendz handbag sale", rel: 'help' do %>
					<span class="visible-sm visible-md visible-lg">Handbags</span><span class="visible-xs cBagG"><%= image_tag 'bag.png' %></span>
				<% end %>
			</li>
			<li class="cLiMenu col-xs-2 col-sm-2 col-md-2 col-lg-2">
				<%= link_to makeup_path, target: '_self', title: "Fashion trendz make up tips", rel: 'help' do %>
					<span class="visible-sm visible-md visible-lg">MakeUp</span><span class="visible-xs cBagG"><%= image_tag 'makeup.png' %></span>
				<% end %>
			</li>
			<li class="cLiMenu col-xs-2 col-sm-2 col-md-2 col-lg-2">
				<%= link_to shoes_path, target: '_self', title: "Fashion trendz shoes, shoes, shoes!!!", rel: 'help' do %>
					<span class="visible-sm visible-md visible-lg">Shoes!</span><span class="visible-xs cBagG"><%= image_tag 'shoes.png' %></span>
				<% end %>
			</li>		
		</ul>

	</div><!-- end of cMenu -->
				</div><!-- for bootstrap -->
			</div><!-- for bootstrap -->
		</div><!-- end of iMenuCont -->
	</div><!-- bootstrap -->
</div><!-- end of cHeader -->
</div><!-- end of iHeaderTopDiv -->	
</div><!-- end of iHeaderCont -->
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= latest_fashion_trendz_blog_title(yield(:title)) %> </title>

 <!-- , 'data-turbolinks-track' => true --> 
  <%= stylesheet_link_tag 'application', media: 'all' %>

 <!-- , 'data-turbolinks-track' => true --> 
  <%= javascript_include_tag 'application' %>
  
  <%= csrf_meta_tags %>

<!-- for ie > 9v  -->
  <%= render 'layouts/ie_shim' %>
<!-- for ie > 9v  -->

<!-- for compatibility with html5Mode in $locationProvider -->
	<base href="/">
</head>
<body>

		<%= render 'layouts/latest_fashion_trendz_blog_header' %>

<!-- including angular -->
		<div id="iPageWrap"  ng-app="trendzDisplay">
	<!--rest of page-->
			<div id="iPageCont">

<!-- flash message & alerts -->
				<div class='container-fluid'>
					<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-6 col-offset-3">
						<% flash.each do |msg_type, msg| %>
							<%= content_tag(:div, msg, class: "alert alert-#{msg_type} cDErr") %>
						<% end %>
					</div>
				</div>			

				<%= yield %>
			</div>
		</div>
		
		<%= render 'layouts/latest_fashion_trendz_blog_footer' %>

<!-- RAILS DEBUGG -->
		<%= debug(params) if Rails.env.development? %>
	<!-- <br> for until i fix footer layout to break for debug -->

</body>
</html>